### ISSUE TITLE
No bower file with the property main

### ISSUE THREAD

**Issue by bluesky777** [isonet/angular-barcode#12]
Hello, great library!! 
I use yeoman, and I installed angular-barcode with:
`bower install angular-barcode-es6 --save`
When I run **grunt serve**, It crashes, and it is because there's no file bower.json with the important param: 
`"main": "dist/angular-barcode.js",`
I created it manually, and my project works again, but when I have to make a 
`bower install` to my project again, I will have to create the bower file again, and It's a problem.
Can you fix this please!!!

PD:
Write in your description the way to install with bower, that would be great.
Sorry my english.

**Comment by isonet** [comment]
Could you provide an example? I have a hard time figuring out your problem. I would also recommend to stop using bower and switch to NPM if possible.

**Comment by bluesky777** [comment]
I've create an empty folder and run `bower install angular-barcode-es6 --save `  and I even don't see the `bower.json` file. It has a `.bower.js` file with this content:

`
{
  "name": "angular-barcode-es6",
  "homepage": "https://github.com/isonet/angular-barcode",
  "version": "2.0.0",
  "_release": "2.0.0",
  "_resolution": {
    "type": "version",
    "tag": "v2.0.0",
    "commit": "8ed3e33ff3cdd0c8103427b5c6bc2a6284e56c6e"
  },
  "_source": "https://github.com/isonet/angular-barcode.git",
  "_target": "^2.0.0",
  "_originalSource": "angular-barcode-es6",
  "_direct": true
}
`

I can't use NPM. Gruntfile.js is configured to join the bower files and add them to the index.html file, but It can't do it if the component doesn't have a bower file and the property "main" with the path to the component itself. Can you add the bower.json file and key "main" please? Excuse my english.

**Comment by isonet** [comment]
I just published a new version and tried it out, it seems like it works now! Apparently I had an error in the bower.json file and was ignoring the dist folder which was referenced in the main property.
Please tell me if everything is working correctly. You will probably have to run `bower update` to get the latest version.

**Comment by bluesky777** [comment]
Wow, It works now. Thank you so much!!

**Comment by isonet** [comment]
Awesome :smile:
