### ISSUE TITLE
Please add to bower library

### ISSUE THREAD

**Issue by spyhunter88** [isonet/angular-barcode#6]
It's good to add to bower library.
I can not find this lib, and the latest I can use is angular-barcode from justechn that stops nearly a year.
And I found an issue with this when print out, the barcode still be blurry in Chrome.

**Comment by isonet** [comment]
I just added it to bower, but angular-barcode was already taken, so now it's `angular-barcode-es6`.

What type are you using that produces the blurry image? image, canvas or svg?

**Comment by spyhunter88** [comment]
Thanks for that, I just copied your code into my project and it works good.
Anw, `angular-barcode` does not allow me to choose type, I can not remember which type it use.
