### ISSUE TITLE
Question about barcode of long size

### ISSUE THREAD

**Issue by yj-kwon** [isonet/angular-barcode#9]
Sometimes, I use very long text of barcode. (about 31)
Then, barcode's width is too long to show in mobile screen.

[length: 10]
![screen shot 2017-02-20 at 4 32 02 pm](https://cloud.githubusercontent.com/assets/25316216/23115783/799e35ca-f78a-11e6-89b8-430d44c84f1b.png)
[length:30]
![screen shot 2017-02-20 at 4 32 16 pm](https://cloud.githubusercontent.com/assets/25316216/23115787/80448384-f78a-11e6-8cc1-42c3731be6e7.png)

I look into barcode's markup.
There is always 4px gap each barcode.
![screen shot 2017-02-20 at 4 33 19 pm](https://cloud.githubusercontent.com/assets/25316216/23115801/94928778-f78a-11e6-8de3-9de770660903.png)
If length of text is 31, just gap size is 30 * 4 = 120px.

Is there any option for long text?

**Comment by isonet** [comment]
I'm sorry but I don't think that is possible. Maybe this can help you: http://worldbarcodes.com/barcode-standards/
For longer text I would recommend a 2D Data Matrix or QR codes.
